### ISSUE TITLE
Add Custom Apps

### ISSUE THREAD

**Issue by Alfiefe10** [anfreire/updateMe-Mobile#28]
It woukd be great to be able to add apps we wanted to have, for ezamplo other launchers ot iptv apps. We could enter the name of the app and the possible servers as addresses.

**Comment by anfreire** [comment]
Thanks for the suggestion!

A feature where users can input an app name and have it searched across known servers is actually already in the planning stages. You can find more details about it here: [GitHub Issue #27](https://github.com/anfreire/updateMe-Mobile/issues/27#issuecomment-2301776813).

However, this feature will only provide the APK from various sources if found. It won't check for updates since that requires a backend, and most providers can't be scraped on Android.

As for entering server addresses directly, it's not feasible because each website requires a unique scraping script. This might be possible with AI integration in the future, but that's beyond the current scope given my budget and available time.
